version: "3"
services:
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: gateway
    depends_on:
      - users-service
      - customers-service
      - order-service
    networks:
      - yubitech-network

  users-service:
    build:
      context: ../users-service
      dockerfile: Dockerfile
    container_name: users-service
    networks:
      - yubitech-network
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

  customers-service:
    build:
      context: ../customers-service
      dockerfile: Dockerfile
    container_name: customers-service
    networks:
      - yubitech-network
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    container_name: order-service
    networks:
      - yubitech-network
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=yubitech
    container_name: postgres
    networks:
      - yubitech-network
    volumes:
      - ./postgres/backup:/pg-backup
      - ./postgres/data:/var/lib/postgresql/data

networks:
  yubitech-network:
    driver: bridge
